In [57]:
import pandas as pd 
import numpy as np
import glob

In [58]:
from nsepy import get_history
from datetime import date 
import nsepy

In [59]:
# setting the year and duration of data collection

from nsepy.derivatives import get_expiry_date
expiry = get_expiry_date(year=2019, month=12)
expiry

{datetime.date(2019, 12, 5),
 datetime.date(2019, 12, 12),
 datetime.date(2019, 12, 19),
 datetime.date(2019, 12, 26)}

In [77]:
tcs = get_history(symbol='ZEEL',
                   start=date(2015,1,1),
                   end=date(2020,10,21))

In [78]:
tcs

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2015-01-01,ZEEL,EQ,380.75,381.0,381.05,377.05,379.00,377.70,378.33,321140,1.214976e+13,7645,93391,0.2908
2015-01-02,ZEEL,EQ,377.70,378.0,383.50,378.00,379.50,380.95,381.24,960337,3.661218e+13,14605,527004,0.5488
2015-01-05,ZEEL,EQ,380.95,379.1,381.60,377.10,379.80,380.00,379.79,842678,3.200426e+13,26590,388593,0.4611
2015-01-06,ZEEL,EQ,380.00,377.0,378.45,361.20,369.95,367.90,370.26,1443145,5.343422e+13,32994,756677,0.5243
2015-01-07,ZEEL,EQ,367.90,367.9,370.00,360.45,363.90,364.85,363.72,1527500,5.555868e+13,21579,924628,0.6053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-10-15,ZEEL,EQ,186.20,187.0,188.40,178.70,180.20,179.95,183.65,20008768,3.674521e+14,114935,3942133,0.1970
2020-10-16,ZEEL,EQ,179.95,181.5,182.95,173.50,175.30,175.70,176.63,29518941,5.214072e+14,163941,5645280,0.1912
2020-10-19,ZEEL,EQ,175.70,176.7,177.90,173.50,174.20,174.20,174.96,20656092,3.613988e+14,117018,3544485,0.1716
2020-10-20,ZEEL,EQ,174.20,174.2,183.80,173.00,183.00,183.00,181.21,32494248,5.888132e+14,165495,2667824,0.0821
2020-10-21,ZEEL,EQ,183.00,185.0,189.20,176.05,181.00,180.55,183.19,30221784,5.536378e+14,150247,2881945,0.0954

In [9]:
# generate features 

#def features_build(df):
#     df['Date'] = pd.to_datetime(df['Date'])
#     df['Year'] = df['Date'].dt.year
#     df['Month'] = df.Date.dt.month
#     df['Day'] = df.Date.dt.day
#     df['WeekOfYear'] = df.Date.dt.weekofyear

In [79]:
#setting index as date

tcs.insert(0, 'Date',  pd.to_datetime(tcs.index,format='%Y-%m-%d') )

In [80]:
print(type(tcs.index))
print(type(tcs.Date))

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.series.Series'>

In [85]:
tcs

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,,
2015-01-01,2015-01-01,ZEEL,EQ,380.75,381.0,381.05,377.05,379.00,377.70,378.33,321140,1.214976e+13,7645,93391,0.2908
2015-01-02,2015-01-02,ZEEL,EQ,377.70,378.0,383.50,378.00,379.50,380.95,381.24,960337,3.661218e+13,14605,527004,0.5488
2015-01-05,2015-01-05,ZEEL,EQ,380.95,379.1,381.60,377.10,379.80,380.00,379.79,842678,3.200426e+13,26590,388593,0.4611
2015-01-06,2015-01-06,ZEEL,EQ,380.00,377.0,378.45,361.20,369.95,367.90,370.26,1443145,5.343422e+13,32994,756677,0.5243
2015-01-07,2015-01-07,ZEEL,EQ,367.90,367.9,370.00,360.45,363.90,364.85,363.72,1527500,5.555868e+13,21579,924628,0.6053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-10-15,2020-10-15,ZEEL,EQ,186.20,187.0,188.40,178.70,180.20,179.95,183.65,20008768,3.674521e+14,114935,3942133,0.1970
2020-10-16,2020-10-16,ZEEL,EQ,179.95,181.5,182.95,173.50,175.30,175.70,176.63,29518941,5.214072e+14,163941,5645280,0.1912
2020-10-19,2020-10-19,ZEEL,EQ,175.70,176.7,177.90,173.50,174.20,174.20,174.96,20656092,3.613988e+14,117018,3544485,0.1716
2020-10-20,2020-10-20,ZEEL,EQ,174.20,174.2,183.80,173.00,183.00,183.00,181.21,32494248,5.888132e+14,165495,2667824,0.0821
2020-10-21,2020-10-21,ZEEL,EQ,183.00,185.0,189.20,176.05,181.00,180.55,183.19,30221784,5.536378e+14,150247,2881945,0.0954

In [88]:
tcs.to_csv('/Users/markdetiberiis/Desktop/Stocks_data/tcs.csv')